CREATE TABLE wages(
    year VARCHAR,
    total_employees_all_industries_5 VARCHAR, 
    good_producing_sector_6 VARCHAR, 
    agriculture_7 VARCHAR, 
    forestry_fishing_mining_quarrying_oil_and_gas_8_9 VARCHAR,
    utilities VARCHAR, 
    construction VARCHAR, 
    manufacturing VARCHAR,
    services_producing_sector_10 VARCHAR,
    wholesale_and_retail_trade VARCHAR,
    transportation_and_warehousing VARCHAR,
    finance_insurance_real_estate_rental_and_leasing VARCHAR,
    professional_scientific_and_technical_services VARCHAR, 
    business_building_and_other_support_services_11 VARCHAR,
    educational_services VARCHAR,
    health_care_and_social_assistance VARCHAR,
    information_culture_and_recreation VARCHAR,
    accommodation_and_food_services VARCHAR,
    other_services_except_public_administration VARCHAR,
    public_administration VARCHAR
);
CREATE TABLE cpiCanada (
    date VARCHAR,
    all_items VARCHAR,
    food_4 VARCHAR,
    shelter_5 VARCHAR,
    household_operations_furnishings_and_equipment VARCHAR,
    clothing_and_footwear VARCHAR,
    transportation VARCHAR,
    gasoline VARCHAR,
    health_and_personal_care VARCHAR,
    recreation_education_and_reading VARCHAR,
    alcoholic_beverages_tobacco_products_and_recreational_cannabis VARCHAR,
    all_items_excluding_food_and_energy_6 VARCHAR,
    all_items_excluding_energy_6 VARCHAR,
    energy_6 VARCHAR,
    goods_7 VARCHAR,
    services_8 VARCHAR
);
CREATE TABLE cpiProvincial(
    province VARCHAR, 
    date VARCHAR, 
    all_items VARCHAR,
    food_6 VARCHAR, 
    shelter_7 VARCHAR, 
    household_operations_furnishings_and_equipment VARCHAR, 
    clothing_and_footwear VARCHAR, 
    transportation VARCHAR, 
    gasoline VARCHAR, 
    health_and_personal_care VARCHAR, 
    recreation_education_and_reading VARCHAR,
    alcoholic_beverages_tobacco_products_and_recreational_cannabis VARCHAR, 
    all_items_excluding_food_and_energy_8 VARCHAR, 
    all_items_excluding_energy_8 VARCHAR,
    energy_8 VARCHAR, 
    goods_9 VARCHAR, 
    services_10 VARCHAR
);
CREATE TABLE employmentData (
    date VARCHAR,
    industrial_aggregate_including_unclassified_businesses_6_7 VARCHAR,
    industrial_aggregate_excluding_unclassified_businesses_6_7 VARCHAR,
    goods_producing_industries_8 VARCHAR,
    forestry_logging_and_support_9 VARCHAR,
    mining_quarrying_and_oil_and_gas_extraction VARCHAR,
    utilities VARCHAR,
    construction VARCHAR,
    manufacturing VARCHAR,
    service_producing_industries_10 VARCHAR,
    trade_11 VARCHAR,
    transportation_and_warehousing VARCHAR,
    information_and_cultural_industries VARCHAR,
    finance_and_insurance VARCHAR,
    real_estate_and_rental_and_leasing VARCHAR,
    professional_scientific_and_technical_services VARCHAR,
    management_of_companies_and_enterprises VARCHAR,
    administrative_and_support_waste_management_and_remediation_services VARCHAR,
    educational_services VARCHAR,
    health_care_and_social_assistance VARCHAR,
    arts_entertainment_and_recreation VARCHAR,
    accommodation_and_food_services VARCHAR,
    other_services_except_public_administration VARCHAR,
    public_administration VARCHAR,
    unclassified_businesses_7 VARCHAR
);
CREATE TABLE giniIndexCanada(
    year VARCHAR,
    adjusted_market_income VARCHAR,
    adjusted_total_income VARCHAR,
    adjusted_after_tax_income VARCHAR
);
CREATE TABLE giniIndexProvincial(
    province VARCHAR,
    year VARCHAR,
    adjusted_market_income VARCHAR,
    adjusted_total_income VARCHAR,
    adjusted_after_tax_income VARCHAR
);
CREATE TABLE populationPerProvBothSex(
    province VARCHAR,
    year VARCHAR,
    fifteen_to_sixtyfour_years VARCHAR
);
CREATE TABLE populationPerProvMale(
    province VARCHAR,
    year VARCHAR,
    fifteen_to_sixtyfour_years VARCHAR
);
CREATE TABLE populationPerProvFemale(
    province VARCHAR,
    year VARCHAR,
    fifteen_to_sixtyfour_years VARCHAR
);

CREATE TABLE unemploymentPerProv (
	date VARCHAR,
	newfoundland_and_labrador VARCHAR,
	prince_edward_island VARCHAR,
	nova_scotia VARCHAR,
	new_brunswick VARCHAR,
	quebec VARCHAR,
	ontario VARCHAR,
	manitoba VARCHAR,
	saskatchewan VARCHAR,
	alberta VARCHAR,
	british_columbia VARCHAR,
	yukon_2 VARCHAR,
	northwest_territories_3 VARCHAR,
	nunavut_4 VARCHAR
);

CREATE TABLE unemploymentCanada (
	date VARCHAR,
	Canada VARCHAR
);

CREATE TABLE taxRevenueProvincial (
	province VARCHAR,
	year VARCHAR,
	general_governments_revenue VARCHAR,
	taxes_on_incomes VARCHAR,
	from_households VARCHAR,
	income_taxes VARCHAR,
	wealth_transfer_taxes VARCHAR,
	from_corporations_and_government_business_enterprises_liabilities VARCHAR,
	contributions_to_social_insurance_plans VARCHAR,
	taxes_on_production_and_imports VARCHAR,
	taxes_on_production VARCHAR,
	natural_resource_licences_and_taxes VARCHAR,
	motor_vehicle_licences VARCHAR,
	licences_permits_and_fees VARCHAR,
	real_property_taxes VARCHAR,
	capital_taxes VARCHAR,
	payroll_taxes VARCHAR,
	agricultural_insurance_premiums VARCHAR,
	other_taxes_on_production VARCHAR,
	taxes_on_products VARCHAR,
	sales_taxes VARCHAR,
	general_sales_taxes VARCHAR,
	other_sales_taxes VARCHAR,
	excise_taxes VARCHAR,
	gasoline_and_motive_fuel_taxes VARCHAR,
	tobacco_taxes VARCHAR,
	amusement_taxes VARCHAR,
	land_transfer_taxes VARCHAR,
	liquor_gallonage_taxes VARCHAR,
	other_excise_taxes VARCHAR,
	liquor_trading_profits VARCHAR,
	gaming_trading_profits VARCHAR,
	other_current_transfers_from_households VARCHAR,
	motor_vehicle_and_drivers_licences VARCHAR,
	health_insurance_premiums VARCHAR,
	other_transfers_from_households VARCHAR,
	current_transfers_from_non_profit_institutions_serving_households VARCHAR,
	current_transfers_from_general_governments VARCHAR,
	from_federal_general_government VARCHAR,
	from_local_general_governments VARCHAR,
	investment_income VARCHAR,
	royalties VARCHAR,
	interest_and_other_investment_income VARCHAR,
	sales_of_goods_and_services VARCHAR,
	capital_transfers VARCHAR,
	from_general_governments VARCHAR,
	from_federal_general_government2 VARCHAR,
	final_expenditure_on_goods_and_services VARCHAR,
	of_which_medicare VARCHAR,
	current_transfers_to_households VARCHAR,
	social_assistance VARCHAR,
	income_maintenance VARCHAR,
	other_social_assistance VARCHAR,
	social_insurance_benefits_workers_compensation VARCHAR,
	social_insurance_benefits_other VARCHAR,
	other_current_transfers_to_households VARCHAR,
	current_transfers_to_non_profit_institutions_serving_households VARCHAR,
	subsidies VARCHAR,
	subsidies_on_products_and_imports VARCHAR,
	agriculture VARCHAR,
	non_agriculture VARCHAR,
	subsidies_on_factors_of_production VARCHAR,
	non_agriculture2 VARCHAR,
	current_transfers_to_general_governments  VARCHAR,
	to_federal_general_government VARCHAR,
	to_local_general_governments VARCHAR,
	to_aboriginal_general_governments VARCHAR,
	capital_transfers2 VARCHAR,
	to_households VARCHAR,
	to_business VARCHAR,
	to_general_governments VARCHAR,
	to_local_general_governments2 VARCHAR,
	interest_on_debt VARCHAR,
	fixed_capital VARCHAR,
	new_capital VARCHAR,
	inventories VARCHAR
);

CREATE TABLE taxRevenueCanada (
	date VARCHAR,
	general_governments_revenue VARCHAR,
	taxes_on_incomes VARCHAR,
	from_households VARCHAR,
	income_taxes VARCHAR,
	from_corporations_and_government_business_enterprises_liabilities VARCHAR,
	from_non_residents_withholding_taxes VARCHAR,
	contributions_to_social_insurance_plans VARCHAR,
	of_which_employer_and_employee_contributions_to_employment_insurance VARCHAR,
	taxes_on_production_and_imports VARCHAR,
	taxes_on_production VARCHAR,
	other_taxes_on_production VARCHAR,
	taxes_on_products VARCHAR,
	custom_import_duties VARCHAR,
	sales_taxes VARCHAR,
	goods_and_services_tax_gst VARCHAR,
	excise_taxes VARCHAR,
	excise_duties VARCHAR,
	gasoline_and_motive_fuel_taxes VARCHAR,
	air_travellers_security_charge VARCHAR,
	parimutuel_supervision VARCHAR,
	other_excise_taxes VARCHAR,
	federal_provincial_lottery_agreement VARCHAR,
	other_current_transfers_from_households VARCHAR,
	current_transfers_from_general_governments VARCHAR,
	from_provincial_and_territorial_general_governments VARCHAR,
	other_current_transfers_from_non_residents VARCHAR,
	investment_income VARCHAR,
	royalties VARCHAR,
	interest_and_other_investment_income VARCHAR,
	remitted_profits_of_government_business_enterprises VARCHAR,
	sales_of_goods_and_services VARCHAR,
	capital_transfers VARCHAR,
	from_households2 VARCHAR,
	from_non_profit_institutions_serving_households VARCHAR,
	from_business VARCHAR,
	from_general_governments VARCHAR,
	final_expenditure_on_goods_and_services VARCHAR,
	non_defence VARCHAR,
	defence VARCHAR,
	current_transfers_to_households VARCHAR,
	family_and_youth_allowances VARCHAR,
	child_tax_benefit  VARCHAR,
	universal_childcare_benefit VARCHAR,
	employment_insurance_benefits VARCHAR,
	old_age_security VARCHAR,
	goods_and_services_tax_credit VARCHAR,
	military_veterans_benefits VARCHAR,
	research_and_scholarship_grants VARCHAR,
	other_current_transfers_to_households VARCHAR,
	current_transfers_to_non_profit_institutions_serving_households VARCHAR,
	subsidies VARCHAR,
	subsidies_on_products_and_imports VARCHAR,
	agriculture VARCHAR,
	non_agriculture VARCHAR,
	subsidies_on_factors_of_production VARCHAR,
	non_agriculture2 VARCHAR,
	current_transfers_to_general_governments VARCHAR,
	to_provincial_and_territorial_general_governments VARCHAR,
	taxation_agreements VARCHAR,
	canada_health_transfer VARCHAR,
	canada_social_transfer VARCHAR,
	territorial_governments VARCHAR,
	official_languages VARCHAR,
	other_transfers_to_provincial_and_territorial_general_governments VARCHAR,
	to_local_general_governments VARCHAR,
	to_aboriginal_general_governments VARCHAR,
	current_transfers_to_non_residents VARCHAR,
	contributions_and_aid VARCHAR,
	pension_benefits_and_other VARCHAR,
	capital_transfers2 VARCHAR,
	to_households VARCHAR,
	to_non_profit_institutions_serving_households VARCHAR,
	to_business VARCHAR,
	to_general_governments VARCHAR,
	to_provincial_and_territorial_general_governments2 VARCHAR,
	to_local_general_governments2 VARCHAR,
	to_non_residents VARCHAR,
	interest_on_debt VARCHAR,
	fixed_capital VARCHAR,
	new_capital VARCHAR,
	existing_capital VARCHAR,
	inventories VARCHAR
);

